### PR TITLE
[unitaryhack] Evaluator: Raise if bitcode contains unknown external functions.

### LINKED ISSUE #122: pyqir-evaluator should gracefully fail when bitcode contains unknown external functions
**Describe the bug**

When an LLVM file contains declarations of external functions that are unknown, the evaluator crashes without displaying an error message or raising an Exception.

Issue related to #121.

**To Reproduce**

Use an LLVM file that contains unknown external functions, such as:

```
%String = type opaque

declare %String* @__quantum__rt__bool_to_string(i1)

define void @main() #1 {
entry:
  call %String* @__quantum__rt__bool_to_string(i1 1)
  ret void
}

attributes #1 = { "EntryPoint" }
```

This evaluation does not reach the end and throws no Exception:
```
from pyqir.evaluator import GateLogger, NonadaptiveEvaluator

print("Start")

try:
    NonadaptiveEvaluator().eval("CrashMe.ll", GateLogger())
except Exception as e:
    print("An exception was raised.")

print("End")
```

**Expected behavior**

The evaluator should either:
* Handle them in a transparent manner (if possible)
* Display an error message ("Unsupported function...")
* Raise an exception

### PR DESCRIPTION
**Pull request by georgios-ts**
### Summary
This commit updates the evaluator to detect and raise an appropriate error message
if an input LLVM file contains declarations of unknown external functions.

Closes #122

### CODE REVIEW

File: qirlib/src/evaluation/jit.rs [hunk 1]
```diff
@@ -116,7 +118,7 @@ fn is_entry_point(function: FunctionValue) -> bool {
         .is_some()
 }
 
-fn module_functions<'ctx>(module: &Module<'ctx>) -> impl Iterator<Item = FunctionValue<'ctx>> {
+pub fn module_functions<'ctx>(module: &Module<'ctx>) -> impl Iterator<Item = FunctionValue<'ctx>> {
```
Comment (idavis) [inline qirlib/src/evaluation/jit.rs:121]: Should probably leave this as `pub(crate)` for now. I'm not sure we want to make this externally visible yet.

File: qirlib/src/evaluation/jit.rs [hunk 2]
```diff
@@ -254,6 +257,23 @@ mod tests {
         Ok(())
     }
 
+    #[serial]
+    #[test]
+    fn fails_if_unknown_external_func() -> Result<(), String> {
```
Comment (idavis) [inline qirlib/src/evaluation/jit.rs:262]: If would be good to see a test in Python to verify that the error comes through correctly.

File: qirlib/src/evaluation/runtime.rs [hunk 3]
```diff
@@ -11,20 +11,28 @@ use log;
...
 }
 
 impl<'ctx> Simulator {
-    pub fn new(module: &Module<'ctx>, ee: &ExecutionEngine<'ctx>) -> Self {
+    pub fn new(module: &Module<'ctx>, ee: &ExecutionEngine<'ctx>) -> Result<Self, String> {
         let simulator = Simulator {
             _scope: crate::evaluation::gates::GateScope::new(),
         };
 
+        if let Some(f) = Simulator::unsupported_function(module) {
```
Comment (idavis) [inline qirlib/src/evaluation/runtime.rs:26]: Can we return a list of unsupported functions as string rather than the just the first? From a user perspective it might be helpful to tell them all at once rather than making them re-run each time to find functions that need to be trimmed out.

File: qirlib/src/evaluation/runtime.rs [hunk 4]
```diff
@@ -33,6 +41,15 @@ impl<'ctx> Simulator {
         gs.get_model()
     }
 
+    fn unsupported_function(module: &Module<'ctx>) -> Option<FunctionValue<'ctx>> {
+        module_functions(module).find(|f| {
+            let name = f.get_name().to_str().unwrap();
```
Comment (idavis) [inline qirlib/src/evaluation/runtime.rs:46]: Is there a safe way to avoid panicking during the `unwrap` here?

**Review by idavis — CHANGES_REQUESTED** [review]
Overall, this looks good, just a few items I'd like to discuss. Thank you for your hard work.

File: qirlib/src/evaluation/jit.rs (hunk 1 above)
Comment (georgios-ts) [reply qirlib/src/evaluation/jit.rs]: Good point, done in 76361cc.

File: qirlib/src/evaluation/runtime.rs (hunk 3 above)
Comment (georgios-ts) [reply qirlib/src/evaluation/runtime.rs]: Done in 76361cc.

File: qirlib/src/evaluation/jit.rs (hunk 2 above)
Comment (georgios-ts) [reply qirlib/src/evaluation/jit.rs:264]: Done in f65e76f.

File: qirlib/src/evaluation/runtime.rs (hunk 4 above)
Comment (georgios-ts) [reply qirlib/src/evaluation/runtime.rs:45]: Since this only fails if a function name contains non-utf8 chars (according to the docs https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.to_str), I assumed that we'd fail before reaching this point (probably while loading the module) and we're safe calling `unwrap` here.

If you're still thinking that this is a problem, we could catch and propagate the error.

File: pyqir-evaluator/tests/test_unknown_external_func.py [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+            call %String* @__quantum__rt__bool_to_string(i1 1)
+            ret void
+        }
+
+        attributes #1 = { "EntryPoint" }
+    """
+
+    evaluator = NonadaptiveEvaluator()
+    logger = GateLogger()
+    with pytest.raises(OSError):
```
Comment (idavis) [inline pyqir-evaluator/tests/test_unknown_external_func.py:29]: Is OSError the correct type for the error?

Comment (idavis) [inline pyqir-evaluator/tests/test_unknown_external_func.py:29]: Is OSError the correct type for the error?

File: pyqir-evaluator/tests/test_unknown_external_func.py [hunk 6]
```diff
@@ -0,0 +1,33 @@
+# Copyright (c) Microsoft Corporation.
+# Licensed under the MIT License.
+
+from pyqir.evaluator import GateLogger, NonadaptiveEvaluator
+import pytest
+import tempfile
+
+
```
Comment (idavis) [inline pyqir-evaluator/tests/test_unknown_external_func.py:8]: This is looking great. I think we need a test case for use of multiple non-supported calls.

**Review by idavis — CHANGES_REQUESTED** [review]

File: pyqir-evaluator/tests/test_unknown_external_func.py (hunk 6 above)
Comment (georgios-ts) [reply pyqir-evaluator/tests/test_unknown_external_func.py:8]: Done in d9741dd

File: pyqir-evaluator/tests/test_unknown_external_func.py (hunk 5 above)
Comment (georgios-ts) [reply pyqir-evaluator/tests/test_unknown_external_func.py]: It's what we're currently raising. https://github.com/qir-alliance/pyqir/blob/main/pyqir-evaluator/src/python.rs#L101
It's probably not the best choice for every possible error path (e.g multiple entry points in module) but changing this would require keeping information from where the error originated (and not just a string) so we can raise the appropriate error type in Python. I feel it's a bit outside of the scope of this PR.

File: pyqir-evaluator/tests/test_unknown_external_func.py [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+    logger = GateLogger()
+    with pytest.raises(OSError) as excinfo:
+        with tempfile.NamedTemporaryFile("wt", suffix=".ll") as fd:
+            fd.write(content)
+            fd.flush()
+            evaluator.eval(fd.name, logger)
+    assert str(excinfo.value) == "Unsupported functions `__quantum__rt__bool_to_string`."
+
+
+def test_unknown_external_func():
```
Comment (idavis) [inline pyqir-evaluator/tests/test_unknown_external_func.py:37]: This is a redefinition of the above function and needs to be renamed.

**Review by idavis — CHANGES_REQUESTED** [review]

**Comment by idavis** [comment]
@georgios-ts This just needs to be updated as the antlr pr was merged. Then it should be good to go.

**Review by idavis — APPROVED** [review]
